#!/bin/sh
# HOME NET Cudy
# Event Runner dispatcher
# Версия: 1.4.1-dev
#
# Не выполняет recovery.
# Передает события отдельным обработчикам в будущем.

EVENT_MONITOR="/usr/bin/podkop-event-monitor"

run_monitor() {
    [ -x "$EVENT_MONITOR" ] && "$EVENT_MONITOR"
}

run_monitor
exit $?
