#!/bin/sh /etc/rc.common
# HOME NET Cudy
# Автозапуск службы мониторинга Podkop
# Версия: 1.3.9

START=110
STOP=10

USE_PROCD=1

start_service() {
    procd_open_instance

    procd_set_param command /usr/bin/podkop-service-health-daemon

    procd_set_param respawn 3600 5 0

    procd_set_param stdout 1
    procd_set_param stderr 1

    procd_close_instance
}
